#!/usr/bin/env bash
# display information about subdomains.

	if [ "$#" -eq 1 ]
	then
		for i in "www" "lb-01" "web-01" "web-02"
		do
			str=$(dig +noall +answer "$i.$1")
			registro=$(echo "$str"| awk '{ print $4 }')
			dest=$(echo "$str"| awk '{ print $5 }')
			echo "The subdomain $i is a $registro record and points to $dest"
		done
		exit 1
	fi
	for var in "$@"
	do
		if [ "$1" != "$var" ]
		then
			dig +noall +answer "$var.$1"
		fi
	done