#!/usr/bin/env bash
# Install nginx web server
sudo apt-get -y update && sudo apt-get -y install nginx
sudo service nginx start
sudo echo "Holberton School" | sudo tee /var/www/html/index.html
sudo echo -e "server {
                listen 80 default_server;
                root /var/www/html;
                index index.html index.htm;
}" | sudo tee /etc/nginx/sites-available/www
sudo ln -sf /etc/nginx/sites-available/www /etc/nginx/sites-enabled/
sudo service nginx restart
