#!/usr/bin/env bash
# Install nginx web server
apt-get -y update && apt-get -y install nginx
echo "Holberton School" | sudo tee /srv/www/index.html
echo -e "server {
                listen 80 default_server;
                root /srv/www;
                index index.html index.htm;
}" | sudo tee /etc/nginx/sites-available/www
ln -sf /etc/nginx/sites-available/www /etc/nginx/sites-enabled/
service nginx restart
