#!/usr/bin/env bash
# Install nginx web server and redirect
apt-get -y update && apt-get -y install nginx
echo "Holberton School" | sudo tee /srv/www/index.html
echo -e "server {
                listen 80 default_server;
                root /srv/www;
                index index.html index.htm;

                location /redirect_me {
                    return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
                }
}" | sudo tee /etc/nginx/sites-available/www
ln -sf /etc/nginx/sites-available/www /etc/nginx/sites-enabled/
service nginx restart
