#!/usr/bin/env bash
# Install nginx web server and redirect
apt-get -y update && apt-get -y install nginx
sed -i '46 i \\trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
ln -sf /etc/nginx/sites-available/www /etc/nginx/sites-enabled/
service nginx restart
