#!/usr/bin/env bash
# Install nginx web server and custom 404 error
apt-get -y update && apt-get -y install nginx
echo "Ceci n'est pas une page" | sudo tee /srv/www/custom_404.html
echo "Holberton School" | sudo tee /srv/www/index.html
echo -e "server {
                listen 80 default_server;
                root /srv/www;
                index index.html index.htm;

                location /redirect_me {
                    return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
                }

                error_page 404 /custom_404.html;
                location = /custom_404.html {
                    root /srv/www;
                    internal;
                }
}" | sudo tee /etc/nginx/sites-available/www
ln -sf /etc/nginx/sites-available/www /etc/nginx/sites-enabled/
service nginx restart
