#!/usr/bin/env bash
# generates a MySQL dump and creates a compressed archive
if [[ $# -eq 0 ]] ; then
    echo 'Password for mysql'
    exit 1
fi
mysql -uroot -p"$1" -e "FLUSH TABLES WITH READ LOCK; SHOW MASTER STATUS;"
mysqldump --all-databases --single-transaction --quick > backup.sql -uroot -p"root"
mysql -uroot -p"$1" -e "UNLOCK TABLES;"
tar czf ./"$(date +%Y-%m-%d)".tar.gz ./backup.sql
